name: agile_dev_2022
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:


  flutter:
    sdk: flutter
  circular_menu: ^1.2.3
  get_it: ^7.2.0
  flutter_spinkit: ^5.1.0
  cupertino_icons: ^1.0.2
  drift: ^1.5.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.0
  nice_buttons: ^0.0.2
  google_fonts: ^2.3.2
  test: any
  syncfusion_flutter_charts: ^20.1.52
  desktop_window: ^0.4.0
  week_of_year: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: ^1.5.2
  build_runner: ^2.1.8

flutter:

  uses-material-design: true

